// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADqhW0yn8OAcOBMKGq7M6QJdIAyNvtXC0',
    appId: '1:887457437824:web:05984afeeee474462cae65',
    messagingSenderId: '887457437824',
    projectId: 'gamernotes-mtn-dew-backend',
    authDomain: 'gamernotes-mtn-dew-backend.firebaseapp.com',
    storageBucket: 'gamernotes-mtn-dew-backend.appspot.com',
    measurementId: 'G-3QP8TCRB1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz0yzcF49jIcNTU6AQpNPkTH9PyEUWPfM',
    appId: '1:887457437824:android:dc6f6d6a9efec6c52cae65',
    messagingSenderId: '887457437824',
    projectId: 'gamernotes-mtn-dew-backend',
    storageBucket: 'gamernotes-mtn-dew-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD62I7rmEfgAV_SAb80KLiMJrf_9zHtZKc',
    appId: '1:887457437824:ios:5eadc11c641eaf242cae65',
    messagingSenderId: '887457437824',
    projectId: 'gamernotes-mtn-dew-backend',
    storageBucket: 'gamernotes-mtn-dew-backend.appspot.com',
    iosClientId: '887457437824-dh9eidu4374dd7rnlpi85dleq61gg9r7.apps.googleusercontent.com',
    iosBundleId: 'mtn.dew.gamernotes',
  );
}
